import { StyleSheet } from 'react-native';

import { BORDER_RADIUS, COLORS, FONT_SIZES, SPACING } from '@/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  flex: {
    flex: 1,
  },
  screen: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContent: {
    paddingHorizontal: SPACING.screenHorizontal,
    paddingTop: SPACING.md,
    paddingBottom: SPACING.xxl,
    rowGap: SPACING.lg,
  },
  headerCard: {
    borderRadius: 32,
    backgroundColor: COLORS.foodHeaderOrange,
    padding: SPACING.md,
    rowGap: SPACING.md,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: SPACING.sm,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: BORDER_RADIUS.full,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.whiteAlpha30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitleBlock: {
    flex: 1,
    rowGap: SPACING.xxs,
  },
  headerTitle: {
    color: COLORS.white,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '800',
  },
  headerSubtitle: {
    color: COLORS.white,
    fontSize: FONT_SIZES.sm,
    fontWeight: '600',
  },
  dateSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    columnGap: SPACING.sm,
    borderRadius: BORDER_RADIUS.card,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
    backgroundColor: COLORS.whiteAlpha10,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.whiteAlpha20,
  },
  dateSelectorIconWrap: {
    width: 36,
    height: 36,
    borderRadius: BORDER_RADIUS.full,
    backgroundColor: COLORS.whiteAlpha20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateSelectorTextWrap: {
    flex: 1,
    rowGap: SPACING.xxs,
  },
  dateSelectorLabel: {
    color: COLORS.white,
    fontSize: FONT_SIZES.xs,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  dateSelectorValue: {
    color: COLORS.white,
    fontSize: FONT_SIZES.md,
    fontWeight: '700',
  },
  sectionCard: {
    backgroundColor: COLORS.surface,
    borderRadius: BORDER_RADIUS.card,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.borderSubtle,
    padding: SPACING.md,
    rowGap: SPACING.md,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    columnGap: SPACING.sm,
  },
  sectionTitle: {
    fontSize: FONT_SIZES.lg,
    fontWeight: '800',
    color: COLORS.textPrimary,
  },
  sectionSubtitle: {
    fontSize: FONT_SIZES.sm,
    fontWeight: '600',
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  chart: {
    marginLeft: -SPACING.xs,
    borderRadius: BORDER_RADIUS.card,
  },
  loadingWrap: {
    minHeight: 200,
    alignItems: 'center',
    justifyContent: 'center',
    rowGap: SPACING.sm,
  },
  loadingText: {
    color: COLORS.textSecondary,
    fontSize: FONT_SIZES.sm,
    fontWeight: '600',
  },
  emptyChartState: {
    minHeight: 220,
    alignItems: 'center',
    justifyContent: 'center',
    rowGap: SPACING.sm,
    paddingHorizontal: SPACING.lg,
  },
  emptyHistoryState: {
    paddingVertical: SPACING.md,
  },
  emptyStateText: {
    color: COLORS.textSecondary,
    fontSize: FONT_SIZES.sm,
    fontWeight: '600',
    textAlign: 'center',
  },
  summaryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.sm,
  },
  summaryCard: {
    flexGrow: 1,
    flexBasis: '45%',
    minWidth: 120,
    borderRadius: BORDER_RADIUS.lg,
    backgroundColor: COLORS.journalPillBackground,
    padding: SPACING.md,
    rowGap: SPACING.xxs,
  },
  summaryValue: {
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '800',
    color: COLORS.textPrimary,
  },
  summaryLabel: {
    fontSize: FONT_SIZES.sm,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  waterTrackerCard: {
    borderRadius: BORDER_RADIUS.card,
    backgroundColor: COLORS.journalPillBackground,
    padding: SPACING.md,
    rowGap: SPACING.md,
  },
  waterStepperRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    columnGap: SPACING.md,
  },
  waterCircleButton: {
    width: 52,
    height: 52,
    borderRadius: BORDER_RADIUS.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.foodHeaderOrange,
  },
  waterValueWrap: {
    alignItems: 'center',
    rowGap: SPACING.xxs,
  },
  waterValueText: {
    color: COLORS.textPrimary,
    fontSize: 36,
    lineHeight: 44,
    fontWeight: '800',
  },
  waterValueUnit: {
    color: COLORS.textSecondary,
    fontSize: FONT_SIZES.sm,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  tagSection: {
    rowGap: SPACING.sm,
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.sm,
  },
  tagChip: {
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.sm,
    borderRadius: BORDER_RADIUS.chip,
    backgroundColor: COLORS.inputBackground,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.borderSubtle,
  },
  tagChipSelected: {
    backgroundColor: COLORS.foodHeaderOrange,
    borderColor: COLORS.foodHeaderOrange,
  },
  tagText: {
    color: COLORS.textPrimary,
    fontSize: FONT_SIZES.md,
    fontWeight: '700',
  },
  tagTextSelected: {
    color: COLORS.white,
  },
  satietySection: {
    rowGap: SPACING.sm,
  },
  satietyList: {
    rowGap: SPACING.sm,
  },
  satietyItem: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: SPACING.sm,
    borderRadius: BORDER_RADIUS.lg,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
    backgroundColor: COLORS.surface,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.borderSubtle,
  },
  satietyItemSelected: {
    backgroundColor: COLORS.journalPillBackground,
    borderColor: COLORS.foodHeaderOrange,
  },
  satietyTextBlock: {
    flex: 1,
    rowGap: SPACING.xxs,
  },
  satietyTitle: {
    color: COLORS.textPrimary,
    fontSize: FONT_SIZES.md,
    fontWeight: '800',
  },
  satietySubtitle: {
    color: COLORS.textSecondary,
    fontSize: FONT_SIZES.sm,
    fontWeight: '600',
  },
  satietyIconWrap: {
    width: 46,
    height: 46,
    borderRadius: BORDER_RADIUS.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.socialBg,
  },
  inputLabel: {
    color: COLORS.textPrimary,
    fontSize: FONT_SIZES.md,
    fontWeight: '800',
    marginBottom: SPACING.sm,
  },
  descriptionCard: {
    minHeight: 120,
    borderRadius: BORDER_RADIUS.lg,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.inputBorder,
    backgroundColor: COLORS.journalPillBackground,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
  },
  descriptionInput: {
    minHeight: 104,
    fontSize: FONT_SIZES.md,
    color: COLORS.textPrimary,
    textAlignVertical: 'top',
  },
  submitButton: {
    minHeight: 56,
    borderRadius: BORDER_RADIUS.button,
    backgroundColor: COLORS.buttonPrimary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitButtonDisabled: {
    opacity: 0.65,
  },
  submitContent: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: SPACING.sm,
  },
  submitText: {
    color: COLORS.buttonPrimaryText,
    fontSize: FONT_SIZES.lg,
    fontWeight: '800',
  },
  pickerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: COLORS.overlayDarkMedium,
  },
  pickerCard: {
    position: 'absolute',
    left: SPACING.md,
    right: SPACING.md,
    bottom: SPACING.lg,
    borderRadius: BORDER_RADIUS.card,
    backgroundColor: COLORS.surface,
    paddingBottom: SPACING.sm,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.borderSubtle,
  },
  pickerHeader: {
    alignItems: 'flex-end',
    paddingHorizontal: SPACING.md,
    paddingTop: SPACING.md,
  },
  pickerDoneText: {
    color: COLORS.link,
    fontSize: FONT_SIZES.md,
    fontWeight: '800',
  },
});
