import { StyleSheet } from 'react-native';

import { COLORS } from '@/theme';
import { BORDER_RADIUS, FONT_SIZES, SPACING } from '@/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.journalBackground,
  },
  flex: {
    flex: 1,
  },
  screen: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: SPACING.screenHorizontal,
    paddingTop: SPACING.md,
    paddingBottom: SPACING.xxl,
    rowGap: SPACING.lg,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: SPACING.sm,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: BORDER_RADIUS.full,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.journalIconStroke,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.journalBackground,
  },
  headerLabel: {
    fontSize: FONT_SIZES.md,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  title: {
    fontSize: 34,
    lineHeight: 40,
    fontWeight: '800',
    color: COLORS.textPrimary,
    textAlign: 'center',
    marginTop: SPACING.sm,
  },
  dateSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    backgroundColor: COLORS.surface,
    borderRadius: BORDER_RADIUS.chip,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.primary,
    gap: SPACING.sm,
  },
  dateSelectorText: {
    fontSize: FONT_SIZES.sm,
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  datePickerModal: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  datePickerContainer: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: BORDER_RADIUS.card,
    borderTopRightRadius: BORDER_RADIUS.card,
    paddingBottom: SPACING.lg,
  },
  datePickerHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  datePickerHeaderText: {
    fontSize: FONT_SIZES.md,
    fontWeight: '700',
    color: COLORS.primary,
  },
  mealTypesSection: {
    marginHorizontal: -SPACING.screenHorizontal,
    marginVertical: SPACING.sm,
  },
  mealTypesContainer: {
    paddingHorizontal: SPACING.screenHorizontal,
    columnGap: SPACING.sm,
  },
  mealTypeChip: {
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.sm,
    borderRadius: BORDER_RADIUS.chip,
    backgroundColor: COLORS.inputBackground,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.borderSubtle,
  },
  mealTypeChipSelected: {
    backgroundColor: COLORS.buttonPrimary,
    borderColor: COLORS.buttonPrimary,
  },
  mealTypeText: {
    fontSize: FONT_SIZES.md,
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  mealTypeTextSelected: {
    color: COLORS.buttonPrimaryText,
  },
  selectorSection: {
    backgroundColor: COLORS.surface,
    borderRadius: BORDER_RADIUS.card,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.borderSubtle,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
    rowGap: SPACING.xs,
  },
  satietyRow: {
    minHeight: 74,
    borderRadius: BORDER_RADIUS.lg,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SPACING.sm,
    columnGap: SPACING.sm,
  },
  satietyRowSelected: {
    backgroundColor: COLORS.journalPillBackground,
  },
  satietyTextBlock: {
    flex: 1,
    rowGap: SPACING.xxs,
  },
  satietyTitle: {
    fontSize: FONT_SIZES.md,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  satietySubtitle: {
    fontSize: FONT_SIZES.sm,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  timelineHolder: {
    width: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timelineTrack: {
    width: 4,
    height: 48,
    borderRadius: BORDER_RADIUS.full,
    backgroundColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timelineKnob: {
    width: 20,
    height: 20,
    borderRadius: BORDER_RADIUS.full,
    borderWidth: 3,
    borderColor: COLORS.surface,
  },
  iconHolder: {
    width: 42,
    height: 42,
    borderRadius: BORDER_RADIUS.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.socialBg,
  },
  sectionTitle: {
    fontSize: FONT_SIZES.md,
    fontWeight: '700',
    color: COLORS.textPrimary,
    marginBottom: SPACING.sm,
  },
  descriptionCard: {
    backgroundColor: COLORS.journalPillBackground,
    borderRadius: BORDER_RADIUS.lg,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.inputBorder,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    minHeight: 180,
  },
  descriptionInput: {
    flex: 1,
    minHeight: 120,
    fontSize: FONT_SIZES.md,
    color: COLORS.textPrimary,
    textAlignVertical: 'top',
    marginBottom: SPACING.sm,
  },
  descriptionFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: SPACING.borderWidth,
    borderTopColor: COLORS.inputBorder,
    paddingTop: SPACING.sm,
  },
  toolbarButtons: {
    flexDirection: 'row',
    columnGap: SPACING.sm,
  },
  toolbarButton: {
    width: 32,
    height: 32,
    borderRadius: BORDER_RADIUS.sm,
    backgroundColor: COLORS.inputBackground,
    alignItems: 'center',
    justifyContent: 'center',
  },
  characterCounter: {
    fontSize: FONT_SIZES.sm,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  footer: {
    paddingHorizontal: SPACING.screenHorizontal,
    paddingTop: SPACING.sm,
    paddingBottom: SPACING.lg,
    backgroundColor: COLORS.journalBackground,
  },
  submitButton: {
    minHeight: 58,
    borderRadius: BORDER_RADIUS.button,
    backgroundColor: COLORS.buttonPrimary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitContent: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: SPACING.sm,
  },
  submitText: {
    fontSize: FONT_SIZES.lg,
    fontWeight: '700',
    color: COLORS.buttonPrimaryText,
  },
});
