import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.consultationFeedbackBackground,
  },
  contentContainer: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 28,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.text,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 5,
    elevation: 3,
    marginBottom: 14,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 16,
    marginVertical: 7,
    shadowColor: COLORS.text,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  summaryTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: COLORS.consultationFeedbackTitle,
  },
  summarySubtitle: {
    marginTop: 6,
    fontSize: 14,
    color: COLORS.consultationFeedbackSecondary,
  },
  summaryTime: {
    marginTop: 16,
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.consultationFeedbackTitle,
  },
  summaryDate: {
    marginTop: 4,
    fontSize: 14,
    color: COLORS.consultationFeedbackSecondary,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.consultationFeedbackTitle,
    marginBottom: 12,
  },
  therapistRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.consultationFeedbackAvatar,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  therapistName: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.consultationFeedbackTitle,
  },
  therapistDescription: {
    marginTop: 5,
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.consultationFeedbackSecondary,
    flexShrink: 1,
  },
  ratingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  ratingCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: COLORS.consultationFeedbackDivider,
    backgroundColor: COLORS.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ratingEmoji: {
    fontSize: 22,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.consultationFeedbackDivider,
    borderRadius: 10,
    minHeight: 108,
    paddingHorizontal: 12,
    paddingVertical: 12,
    textAlignVertical: 'top',
    fontSize: 15,
    color: COLORS.consultationFeedbackTitle,
    backgroundColor: COLORS.surface,
  },
  subtitleStrong: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.consultationFeedbackTitle,
  },
  descriptionText: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 21,
    color: COLORS.consultationFeedbackSecondary,
  },
  primaryButton: {
    width: '100%',
    height: 48,
    borderRadius: 10,
    backgroundColor: COLORS.consultationFeedbackPrimary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.white,
  },
  confirmButton: {
    marginTop: 10,
    width: '100%',
    height: 52,
    borderRadius: 12,
    backgroundColor: COLORS.consultationFeedbackPrimary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmButtonText: {
    fontSize: 17,
    fontWeight: '700',
    color: COLORS.white,
  },
});

export default styles;
