// src/screens/booking/TherapistBookingLanding.styles.ts
import { StyleSheet, Dimensions } from 'react-native';
import { COLORS } from '@/theme';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    width: '100%',
    backgroundColor: COLORS.primaryDeeper,
    borderBottomLeftRadius: 44,
    borderBottomRightRadius: 44,
    paddingTop: 48,
    paddingBottom: 36,
    paddingHorizontal: 20,
    position: 'relative',
    overflow: 'hidden',
    zIndex: 2,
  },
  headerTopRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginBottom: 14,
    zIndex: 2,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandText: {
    color: 'rgba(200,230,160,0.9)',
    fontSize: 28,
    fontWeight: '700',
    letterSpacing: 1.5,
    marginBottom: 6,
  },
  subHeader: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 22,
    maxWidth: width * 0.6,
  },
  headerImage: {
    position: 'absolute',
    bottom: 0,
    right: 16,
    width: width * 0.35,
    height: '100%',
    zIndex: 1,
  },
  leafBackground: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    padding: 20,
    paddingTop: 28,
    paddingBottom: 28,
  },
  footerSpacer: {
    flex: 1,
    minHeight: 24,
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  loadingText: {
    fontSize: 13,
    color: COLORS.textSecondary,
    marginLeft: 8,
  },
  therapistCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: COLORS.white,
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.borderSubtle,
    shadowColor: COLORS.shadowBase,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  therapistAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: COLORS.inputBackground,
    marginRight: 14,
  },
  therapistInfo: {
    flex: 1,
    paddingTop: 2,
  },
  therapistLabel: {
    fontSize: 12,
    color: COLORS.primary,
    fontWeight: '700',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  therapistName: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.text,
    lineHeight: 22,
  },
  therapistSpecialization: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginTop: 4,
    lineHeight: 20,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  locationText: {
    fontSize: 13,
    color: COLORS.textSecondary,
    marginLeft: 4,
    flexShrink: 1,
  },
  emptyCard: {
    backgroundColor: COLORS.white,
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: COLORS.borderSubtle,
  },
  emptyCardTitle: {
    color: COLORS.text,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 6,
  },
  emptyCardText: {
    color: COLORS.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  upcomingCard: {
    marginTop: 14,
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: 16,
    shadowColor: COLORS.text,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 5,
  },
  upcomingCardTitle: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
    color: COLORS.text,
  },
  upcomingCardSubtitle: {
    marginTop: 6,
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.textSecondary,
  },
  upcomingTimeDateRow: {
    marginTop: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  upcomingTimeText: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: COLORS.text,
  },
  upcomingDateText: {
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.textSecondary,
  },
  upcomingStatusBadge: {
    marginTop: 14,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: COLORS.consultationFeedbackBackground,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  upcomingStatusText: {
    fontSize: 13,
    lineHeight: 18,
    color: COLORS.consultationFeedbackPrimary,
    fontWeight: '600',
  },
  upcomingCardActionRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-end',
  },
  upcomingCardActionText: {
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '700',
    color: COLORS.text,
  },
  upcomingCardActionIcon: {
    marginLeft: 4,
  },
  footer: {
    marginTop: 0,
    paddingBottom: 28,
    paddingTop: 8,
  },
  actionButton: {
    borderRadius: 28,
    minHeight: 54,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  actionButtonPrimary: {
    backgroundColor: COLORS.buttonGreen,
    shadowColor: COLORS.buttonGreen,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 8,
    elevation: 5,
  },
  actionButtonSecondary: {
    backgroundColor: COLORS.accentNegative,
    marginBottom: 12,
    shadowColor: COLORS.accentNegative,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  actionButtonHistory: {
    backgroundColor: COLORS.buttonPrimary,
    marginBottom: 12,
    shadowColor: COLORS.buttonPrimary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  actionButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '700',
  },
});

export default styles;
