import { StyleSheet } from 'react-native';
import { COLORS } from '@/theme';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.chipSelected,
  },
  container: {
    flex: 1,
    backgroundColor: COLORS.chipSelected,
  },
  contentContainer: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 120,
    gap: 16,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.text,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.14,
    shadowRadius: 6,
    elevation: 4,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: 16,
    shadowColor: COLORS.text,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 5,
  },
  cardTitle: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
    color: COLORS.text,
  },
  cardSubtitle: {
    marginTop: 6,
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.textSecondary,
  },
  timeDateRow: {
    marginTop: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  timeText: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: COLORS.text,
  },
  dateText: {
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.textSecondary,
  },
  statusBadge: {
    marginTop: 14,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: COLORS.consultationFeedbackBackground,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  statusText: {
    fontSize: 13,
    lineHeight: 18,
    color: COLORS.consultationFeedbackPrimary,
    fontWeight: '600',
  },
  joinButton: {
    marginTop: 16,
    width: '100%',
    height: 48,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  joinButtonActive: {
    backgroundColor: COLORS.warning,
  },
  joinButtonDisabled: {
    backgroundColor: COLORS.placeholder,
  },
  joinButtonText: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: COLORS.text,
  },
  helperText: {
    marginTop: 8,
    fontSize: 13,
    lineHeight: 18,
    color: COLORS.textSecondary,
  },
  errorText: {
    marginTop: 8,
    fontSize: 13,
    lineHeight: 18,
    color: COLORS.errorText,
  },
  reminderText: {
    marginTop: 8,
    fontSize: 12,
    lineHeight: 16,
    color: COLORS.errorText,
    fontStyle: 'italic',
    textAlign: 'center',
  },
  floatingContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 20,
    backgroundColor: COLORS.chipSelected,
  },
  floatingButton: {
    width: '100%',
    height: 52,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    shadowColor: COLORS.text,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 6,
  },
  floatingButtonPrimary: {
    backgroundColor: COLORS.warning,
  },
  floatingButtonSecondary: {
    backgroundColor: COLORS.primary,
  },
  floatingButtonText: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: COLORS.text,
  },
  floatingButtonTextSecondary: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: COLORS.white,
  },
  infoTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    color: COLORS.facebook,
  },
  reasonText: {
    marginTop: 10,
    fontSize: 14,
    lineHeight: 22,
    color: COLORS.text,
  },
  therapistCard: {
    marginTop: 12,
    backgroundColor: COLORS.white,
    borderRadius: 15,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: COLORS.text,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 2,
  },
  therapistImage: {
    width: 74,
    height: 74,
    borderRadius: 12,
    backgroundColor: COLORS.inputBackground,
  },
  therapistInfo: {
    marginLeft: 12,
    flex: 1,
  },
  therapistName: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    color: COLORS.text,
  },
  therapistSpecialty: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginBottom: 6,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  locationText: {
    marginLeft: 4,
    fontSize: 13,
    color: COLORS.textSecondary,
  },
  availableSlotsLoadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  availableSlotsLoadingText: {
    marginTop: 0,
    marginLeft: 8,
  },
  availableSlotsDateGroup: {
    marginTop: 14,
  },
  availableSlotsDateLabel: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    color: COLORS.text,
    marginBottom: 8,
  },
  availableSlotsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  availableSlotButton: {
    width: '31%',
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 11,
    marginBottom: 10,
    marginHorizontal: '1.1%',
  },
  availableSlotButtonSelected: {
    backgroundColor: COLORS.buttonPrimary,
    borderColor: COLORS.buttonPrimary,
  },
  availableSlotButtonUnselected: {
    backgroundColor: COLORS.white,
    borderColor: COLORS.border,
  },
  availableSlotButtonText: {
    fontSize: 13,
    fontWeight: '600',
  },
  availableSlotButtonTextSelected: {
    color: COLORS.white,
  },
  availableSlotButtonTextUnselected: {
    color: COLORS.text,
  },
});

export default styles;