import { StyleSheet } from 'react-native';
import { COLORS } from '@/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.primaryDeeper,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  circle1: {
    position: 'absolute',
    top: -80,
    right: -60,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: COLORS.splashCircle,
  },
  circle2: {
    position: 'absolute',
    bottom: -60,
    left: -40,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: COLORS.splashCircle,
  },
  circle3: {
    position: 'absolute',
    bottom: 80,
    right: -20,
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: COLORS.splashCircle,
  },
  logoWrap: {
    alignItems: 'center',
    marginBottom: 16,
  },
  logoMark: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: COLORS.splashLogoMarkBg,
    borderWidth: 2,
    borderColor: COLORS.splashLogoMarkBorder,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  logoU: {
    position: 'absolute',
    fontSize: 36,
    fontWeight: '700',
    color: COLORS.splashLogoU,
    top: 20,
    left: 22,
  },
  logoM: {
    fontSize: 36,
    fontWeight: '700',
    color: COLORS.splashLogoText,
    marginTop: 8,
  },
  wordmark: {
    fontSize: 48,
    fontWeight: '700',
    color: COLORS.splashLogoText,
    letterSpacing: -1,
  },
  tagline: {
    fontSize: 13,
    fontWeight: '500',
    color: COLORS.splashTagline,
    letterSpacing: 2.5,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  dotsRow: {
    position: 'absolute',
    bottom: 52,
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.splashDot,
  },
});
