import { StyleSheet } from 'react-native';
import { BORDER_RADIUS, COLORS, FONT_SIZES, SPACING } from '@/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContent: {
    flexGrow: 1,
    backgroundColor: COLORS.background,
    paddingBottom: SPACING.xxl,
  },

  /* ==== HERO HEADER ==== */
  heroHeader: {
    backgroundColor: COLORS.primaryDeeper,
    paddingTop: SPACING.screenTop,
    paddingHorizontal: SPACING.screenHorizontal,
    paddingBottom: SPACING.xl,
    borderBottomLeftRadius: 36,
    borderBottomRightRadius: 36,
    overflow: 'hidden',
    position: 'relative',
  },
  heroCircleLarge: {
    position: 'absolute',
    top: -40,
    right: -40,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: COLORS.whiteAlpha08,
  },
  heroCircleSmall: {
    position: 'absolute',
    bottom: -20,
    right: 40,
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: COLORS.whiteAlpha06,
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.lg,
  },
  dateSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
  },
  dateText: {
    fontSize: FONT_SIZES.xs,
    color: COLORS.whiteAlpha70,
    fontWeight: '500',
  },
  notificationButton: {
    position: 'relative',
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.whiteAlpha15,
    borderRadius: 20,
  },
  notificationBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.accentNegative,
    borderWidth: 1.5,
    borderColor: COLORS.primaryDeeper,
  },
  profileSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
  },
  profileAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.border,
    borderWidth: 2.5,
    borderColor: COLORS.whiteAlpha50,
  },
  profileInfo: {
    flex: 1,
  },
  greetingText: {
    fontSize: FONT_SIZES.xl,
    fontWeight: '700',
    color: COLORS.white,
    lineHeight: 28,
  },
  greetingSubtext: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.whiteAlpha75,
    marginTop: 3,
  },

  /* ==== PADDED CONTENT ==== */
  paddedContent: {
    paddingHorizontal: SPACING.screenHorizontal,
    paddingTop: SPACING.lg,
  },

  /* ==== SECTIONS ==== */
  section: {
    marginBottom: SPACING.sectionGap,
  },
  sectionTitle: {
    fontSize: FONT_SIZES.xs,
    fontWeight: '700',
    color: COLORS.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: SPACING.sm,
  },

  /* ==== AI COMPANION CARD ==== */
  companionCard: {
    backgroundColor: COLORS.surfaceRaised,
    borderRadius: BORDER_RADIUS.card,
    paddingVertical: SPACING.xl,
    paddingHorizontal: SPACING.md,
    alignItems: 'center',
    shadowColor: COLORS.primaryDark,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.10,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1.5,
    borderColor: COLORS.borderSubtle,
  },
  companionOrbitContainer: {
    width: 140,
    height: 140,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: SPACING.md,
  },
  companionRingOuter: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 1.5,
    borderColor: COLORS.primaryAlpha18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  companionRingInner: {
    width: 94,
    height: 94,
    borderRadius: 47,
    borderWidth: 1,
    borderColor: COLORS.primaryAlpha35,
    justifyContent: 'center',
    alignItems: 'center',
  },
  companionAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: COLORS.primaryMuted,
    justifyContent: 'center',
    alignItems: 'center',
  },
  companionOrbitDot: {
    position: 'absolute',
    borderRadius: BORDER_RADIUS.pill,
  },
  companionOrbitDot1: {
    width: 9,
    height: 9,
    backgroundColor: COLORS.primaryLight,
    top: 14,
    right: 4,
  },
  companionOrbitDot2: {
    width: 7,
    height: 7,
    backgroundColor: COLORS.primaryMid,
    bottom: 24,
    left: 3,
  },
  companionOrbitDot3: {
    width: 5,
    height: 5,
    backgroundColor: COLORS.primaryAlpha35,
    bottom: 8,
    right: 18,
  },
  companionTitle: {
    fontSize: FONT_SIZES.lg,
    fontWeight: '800',
    color: COLORS.text,
    marginBottom: 6,
  },
  companionStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: SPACING.lg,
  },
  companionOnlineDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: COLORS.accentPositive,
  },
  companionStatusTxt: {
    fontSize: FONT_SIZES.xs,
    color: COLORS.textTertiary,
  },
  companionCTA: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: COLORS.primary,
    borderRadius: BORDER_RADIUS.xl,
    paddingVertical: 13,
    paddingHorizontal: SPACING.xl,
    shadowColor: COLORS.primaryAlpha35,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 3,
  },
  companionCTATxt: {
    fontSize: FONT_SIZES.sm,
    fontWeight: '700',
    color: COLORS.white,
  },

  /* ==== SESSION CARDS ==== */
  sessionsCarousel: {
    gap: SPACING.md,
    paddingRight: SPACING.screenHorizontal,
  },
  sessionCard: {
    width: 185,
    height: 140,
    borderRadius: BORDER_RADIUS.xl,
    overflow: 'hidden',
    shadowColor: COLORS.shadowBase,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.14,
    shadowRadius: 8,
    elevation: 4,
  },
  sessionImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  sessionOverlay: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: COLORS.overlayDark45,
  },
  sessionContent: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: SPACING.md,
  },
  sessionTitle: {
    fontSize: FONT_SIZES.sm,
    fontWeight: '700',
    color: COLORS.white,
  },
  sessionSubtitle: {
    fontSize: FONT_SIZES.xs,
    color: COLORS.whiteAlpha80,
    marginTop: 2,
  },

  /* ==== MOOD CHECK-IN ==== */
  moodSection: {
    marginTop: SPACING.lg,
  },
  moodLabel: {
    fontSize: FONT_SIZES.xs,
    color: COLORS.whiteAlpha70,
    marginBottom: SPACING.sm,
    fontWeight: '500',
  },
  moodChips: {
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  moodChip: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    backgroundColor: COLORS.whiteAlpha10,
    borderWidth: 1.5,
    borderColor: COLORS.whiteAlpha15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quickInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: SPACING.sm,
    gap: SPACING.sm,
  },
  quickInput: {
    flex: 1,
    height: 42,
    borderRadius: 12,
    backgroundColor: COLORS.whiteAlpha12,
    borderWidth: 1,
    borderColor: COLORS.whiteAlpha20,
    paddingHorizontal: SPACING.md,
    color: COLORS.white,
    fontSize: FONT_SIZES.sm,
  },
  quickSendBtn: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: COLORS.whiteAlpha20,
    justifyContent: 'center',
    alignItems: 'center',
  },

  /* ==== BOTTOM SPACER ==== */
  bottomSpacer: {
    height: SPACING.lg,
  },
});
