export const SPACING = {
  xxs: 4,
  xs: 8,
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  xxl: 32,
  xxxl: 40,
  screenHorizontal: 16,
  screenTop: 12,
  sectionGap: 24,
  inputPaddingHorizontal: 16,
  inputPaddingVertical: 14,
  textAreaPadding: 18,
  textAreaMinHeight: 180,
  iconButtonSize: 48,
  imagePreviewSize: 88,
  submitButtonHeight: 56,
  borderWidth: 1,
  statusRowGap: 10,
} as const;
