import { StyleSheet } from 'react-native';

import { BORDER_RADIUS, COLORS, FONT_SIZES, SPACING } from '@/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.sleepHeaderPurple,
  },
  flex: {
    flex: 1,
  },
  screen: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContent: {
    paddingHorizontal: SPACING.screenHorizontal,
    paddingTop: SPACING.md,
    paddingBottom: SPACING.xxl,
    rowGap: SPACING.lg,
  },
  headerCard: {
    borderRadius: 32,
    backgroundColor: COLORS.sleepHeaderPurple,
    padding: SPACING.md,
    rowGap: SPACING.md,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: SPACING.sm,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: BORDER_RADIUS.full,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.whiteAlpha30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitleBlock: {
    flex: 1,
    rowGap: SPACING.xxs,
  },
  headerTitle: {
    color: COLORS.white,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '800',
  },
  headerSubtitle: {
    color: COLORS.white,
    fontSize: FONT_SIZES.sm,
    fontWeight: '600',
  },
  dateSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    columnGap: SPACING.sm,
    borderRadius: BORDER_RADIUS.card,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
    backgroundColor: COLORS.whiteAlpha10,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.whiteAlpha20,
  },
  dateSelectorIconWrap: {
    width: 36,
    height: 36,
    borderRadius: BORDER_RADIUS.full,
    backgroundColor: COLORS.whiteAlpha20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateSelectorTextWrap: {
    flex: 1,
    rowGap: SPACING.xxs,
  },
  dateSelectorLabel: {
    color: COLORS.white,
    fontSize: FONT_SIZES.xs,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  dateSelectorValue: {
    color: COLORS.white,
    fontSize: FONT_SIZES.md,
    fontWeight: '700',
  },
  sectionCard: {
    backgroundColor: COLORS.surface,
    borderRadius: BORDER_RADIUS.card,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.borderSubtle,
    padding: SPACING.md,
    rowGap: SPACING.md,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    columnGap: SPACING.sm,
  },
  sectionTitle: {
    fontSize: FONT_SIZES.lg,
    fontWeight: '800',
    color: COLORS.textPrimary,
  },
  sectionSubtitle: {
    fontSize: FONT_SIZES.sm,
    fontWeight: '600',
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  chart: {
    marginLeft: -SPACING.xs,
    borderRadius: BORDER_RADIUS.card,
  },
  loadingWrap: {
    minHeight: 200,
    alignItems: 'center',
    justifyContent: 'center',
    rowGap: SPACING.sm,
  },
  loadingText: {
    color: COLORS.textSecondary,
    fontSize: FONT_SIZES.sm,
    fontWeight: '600',
  },
  emptyChartState: {
    minHeight: 220,
    alignItems: 'center',
    justifyContent: 'center',
    rowGap: SPACING.sm,
    paddingHorizontal: SPACING.lg,
  },
  emptyHistoryState: {
    paddingVertical: SPACING.md,
  },
  emptyStateText: {
    color: COLORS.textSecondary,
    fontSize: FONT_SIZES.sm,
    fontWeight: '600',
    textAlign: 'center',
  },
  summaryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.sm,
  },
  summaryCard: {
    flexGrow: 1,
    flexBasis: '30%',
    minWidth: 100,
    borderRadius: BORDER_RADIUS.lg,
    backgroundColor: COLORS.journalPillBackground,
    padding: SPACING.md,
    rowGap: SPACING.xxs,
  },
  summaryIconWrap: {
    width: 28,
    height: 28,
    borderRadius: BORDER_RADIUS.full,
    backgroundColor: COLORS.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryValue: {
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '800',
    color: COLORS.textPrimary,
  },
  summaryValueCompact: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '800',
    color: COLORS.textPrimary,
  },
  summaryLabel: {
    fontSize: FONT_SIZES.sm,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  timeRow: {
    flexDirection: 'row',
    columnGap: SPACING.sm,
  },
  timeCard: {
    flex: 1,
    borderRadius: BORDER_RADIUS.lg,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.borderSubtle,
    backgroundColor: COLORS.surface,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
    rowGap: SPACING.xs,
  },
  timeLabel: {
    color: COLORS.textSecondary,
    fontSize: FONT_SIZES.sm,
    fontWeight: '600',
  },
  timeValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  timeValue: {
    color: COLORS.textPrimary,
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '800',
  },
  qualityList: {
    rowGap: SPACING.sm,
  },
  qualityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: SPACING.sm,
    borderRadius: BORDER_RADIUS.lg,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
    backgroundColor: COLORS.surface,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.borderSubtle,
  },
  qualityItemSelected: {
    backgroundColor: COLORS.journalPillBackground,
    borderColor: COLORS.sleepHeaderPurple,
  },
  qualityTextBlock: {
    flex: 1,
    rowGap: SPACING.xxs,
  },
  qualityTitle: {
    color: COLORS.textPrimary,
    fontSize: FONT_SIZES.md,
    fontWeight: '800',
  },
  qualitySubtitle: {
    color: COLORS.textSecondary,
    fontSize: FONT_SIZES.sm,
    fontWeight: '600',
  },
  qualityIconWrap: {
    width: 46,
    height: 46,
    borderRadius: BORDER_RADIUS.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.socialBg,
  },
  inputLabel: {
    color: COLORS.textPrimary,
    fontSize: FONT_SIZES.md,
    fontWeight: '800',
    marginBottom: SPACING.sm,
  },
  noteCard: {
    minHeight: 120,
    borderRadius: BORDER_RADIUS.lg,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.inputBorder,
    backgroundColor: COLORS.journalPillBackground,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
  },
  noteInput: {
    minHeight: 104,
    fontSize: FONT_SIZES.md,
    color: COLORS.textPrimary,
    textAlignVertical: 'top',
  },
  historyList: {
    rowGap: SPACING.sm,
  },
  historyItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    columnGap: SPACING.sm,
    borderRadius: BORDER_RADIUS.lg,
    backgroundColor: COLORS.journalPillBackground,
    padding: SPACING.md,
  },
  historyIconWrap: {
    width: 42,
    height: 42,
    borderRadius: BORDER_RADIUS.full,
    backgroundColor: COLORS.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyContent: {
    flex: 1,
    rowGap: SPACING.xxs,
  },
  historyTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    columnGap: SPACING.sm,
  },
  historyTitleText: {
    flex: 1,
    color: COLORS.textPrimary,
    fontSize: FONT_SIZES.md,
    fontWeight: '800',
  },
  historyMetaText: {
    color: COLORS.textSecondary,
    fontSize: FONT_SIZES.sm,
    fontWeight: '700',
  },
  historySubtitleText: {
    color: COLORS.textSecondary,
    fontSize: FONT_SIZES.sm,
    fontWeight: '600',
  },
  historyNoteText: {
    color: COLORS.textPrimary,
    fontSize: FONT_SIZES.sm,
    fontWeight: '500',
  },
  pickerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: COLORS.overlayDarkMedium,
  },
  pickerCard: {
    position: 'absolute',
    left: SPACING.md,
    right: SPACING.md,
    bottom: SPACING.lg,
    borderRadius: BORDER_RADIUS.card,
    backgroundColor: COLORS.surface,
    paddingBottom: SPACING.sm,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.borderSubtle,
  },
  pickerHeader: {
    alignItems: 'flex-end',
    paddingHorizontal: SPACING.md,
    paddingTop: SPACING.md,
  },
  pickerDoneText: {
    color: COLORS.link,
    fontSize: FONT_SIZES.md,
    fontWeight: '800',
  },
});
