import { StyleSheet } from 'react-native';

import { COLORS } from '@/theme';
import { BORDER_RADIUS, FONT_SIZES, SPACING } from '@/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.journalBackground,
  },
  flex: {
    flex: 1,
  },
  screen: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: SPACING.screenHorizontal,
    paddingTop: SPACING.md,
    paddingBottom: SPACING.xxl,
    rowGap: SPACING.lg,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: SPACING.sm,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: BORDER_RADIUS.full,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.journalIconStroke,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.journalBackground,
  },
  headerLabel: {
    fontSize: FONT_SIZES.md,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  title: {
    fontSize: 34,
    lineHeight: 40,
    fontWeight: '800',
    color: COLORS.textPrimary,
    textAlign: 'center',
    marginTop: SPACING.sm,
  },
  timeRow: {
    flexDirection: 'row',
    columnGap: SPACING.sm,
  },
  timeCard: {
    flex: 1,
    backgroundColor: COLORS.surface,
    borderRadius: BORDER_RADIUS.lg,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.borderSubtle,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
    rowGap: SPACING.xs,
  },
  timeLabel: {
    fontSize: FONT_SIZES.sm,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  timeValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  timeValue: {
    fontSize: FONT_SIZES.xl,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  selectorSection: {
    backgroundColor: COLORS.surface,
    borderRadius: BORDER_RADIUS.card,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.borderSubtle,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
    rowGap: SPACING.xs,
  },
  qualityRow: {
    minHeight: 74,
    borderRadius: BORDER_RADIUS.lg,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SPACING.sm,
    columnGap: SPACING.sm,
  },
  qualityRowSelected: {
    backgroundColor: COLORS.journalPillBackground,
  },
  qualityTextBlock: {
    flex: 1,
    rowGap: SPACING.xxs,
  },
  qualityTitle: {
    fontSize: FONT_SIZES.md,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  qualitySubtitle: {
    fontSize: FONT_SIZES.sm,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  timelineHolder: {
    width: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timelineTrack: {
    width: 4,
    height: 48,
    borderRadius: BORDER_RADIUS.full,
    backgroundColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timelineKnob: {
    width: 20,
    height: 20,
    borderRadius: BORDER_RADIUS.full,
    borderWidth: 3,
    borderColor: COLORS.surface,
  },
  iconHolder: {
    width: 42,
    height: 42,
    borderRadius: BORDER_RADIUS.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.socialBg,
  },
  sectionTitle: {
    fontSize: FONT_SIZES.md,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  noteCard: {
    backgroundColor: COLORS.journalPillBackground,
    borderRadius: BORDER_RADIUS.lg,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.inputBorder,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    minHeight: 130,
  },
  noteInput: {
    flex: 1,
    minHeight: 110,
    fontSize: FONT_SIZES.md,
    color: COLORS.textPrimary,
    textAlignVertical: 'top',
  },
  footer: {
    paddingHorizontal: SPACING.screenHorizontal,
    paddingTop: SPACING.sm,
    paddingBottom: SPACING.lg,
    backgroundColor: COLORS.journalBackground,
  },
  submitButton: {
    minHeight: 58,
    borderRadius: BORDER_RADIUS.button,
    backgroundColor: COLORS.buttonPrimary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitContent: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: SPACING.sm,
  },
  submitText: {
    fontSize: FONT_SIZES.lg,
    fontWeight: '700',
    color: COLORS.buttonPrimaryText,
  },
  iosPickerBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: COLORS.textPrimary,
    opacity: 0.2,
  },
  iosPickerCard: {
    position: 'absolute',
    left: SPACING.md,
    right: SPACING.md,
    bottom: SPACING.lg,
    backgroundColor: COLORS.surface,
    borderRadius: BORDER_RADIUS.card,
    paddingBottom: SPACING.sm,
    paddingHorizontal: SPACING.sm,
    borderWidth: SPACING.borderWidth,
    borderColor: COLORS.borderSubtle,
  },
  iosPickerHeader: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingHorizontal: SPACING.sm,
  },
  iosPickerDone: {
    fontSize: FONT_SIZES.md,
    fontWeight: '700',
    color: COLORS.link,
  },
});
